export const MOUNTAIN_QUERY = `
query{
  mountainGalleryPhotos{
      data{
        attributes{
          title,
          slug,
          image{
            data{
              attributes{
                formats
              }
            }
          }
        }
      }
    }
  }
`
