export const PRODUCT_QUERY = `
query{
    products{
      data{
        attributes{
          title,
          height,
          width,
          key,
          image{
            data{
              attributes{
                formats
              }
            }
          }
        }
      }
    }
  }
`