import Head from 'next/head'
import Image from 'next/image'
import background from 'public/images/HomePageBackground.jpg'
import { Inter } from '@next/font/google'
import { PRODUCT_QUERY } from "../lib/query"

import { useQuery } from 'urql'
import NavBar from '@/components/NavBar'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  //fetch 
  const [results] = useQuery({query:PRODUCT_QUERY})
  const {data, fetching, error} = results
  
  if(fetching) {
    return <p>loading</p>
  }
  if(error) {
    return <p>error o no {error.message}</p>
  }
  const products = data.products.data
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div >
      <NavBar className=''/>
 
      <Image className='object-cover opacity-50'
      fill
      src={background}
    />
   sk lsjlksj dfgsdfg
    {products.map((product)=> <p>{product.attributes.title} 
    <img src={product.attributes.image.data.attributes.formats.small.url} />aaaaaaaaaaaaaaaa </p>)}
  
   sdf
   g 
   sdfg 
   sd
   fg 
   sd
   fg 
   sdf
   g 
   sdfg   
</div>
    </>
  )
}

